# Generated by Django 5.2.12 on 2026-03-08 10:24

from datetime import timedelta

from django.db import migrations, models


def backfill_sla_fields(apps, schema_editor):
    Ticket = apps.get_model("tickets", "Ticket")
    sla_hours = {
        "low": 72,
        "medium": 24,
        "high": 8,
        "critical": 4,
    }
    resolved_statuses = {"closed", "rejected"}

    for ticket in Ticket.objects.filter(sla_deadline_at__isnull=True).iterator():
        updates = []

        ticket.sla_deadline_at = ticket.created_at + timedelta(
            hours=sla_hours.get(ticket.priority, sla_hours["medium"])
        )
        updates.append("sla_deadline_at")

        if ticket.status in resolved_statuses and ticket.resolved_at is None:
            ticket.resolved_at = ticket.updated_at or ticket.created_at
            updates.append("resolved_at")

        ticket.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_auditlog_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_deadline_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_sla_fields, migrations.RunPython.noop),
    ]
